# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinfo',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
